version: '3'

services:
  redis:
      image: redis:6
      ports:
        - 6379:6379
        
  server1:
    build: .
    ports:
      - "3000:3000"
  
  server2:
    build: .
    ports:
      - "3001:3000"